### ISSUE TITLE
Faster (re-)synchronization

### ISSUE THREAD

**Issue by Montellese** [Montellese/mediaimporter.plex#10]
What can be done to improve (re-)synchronization after Kodi has been (re-)started? Retrieving all items and letting Kodi's media import logic handle the changeset detection and synchronization might be too slow for large libraries.

**Comment by enen92** [comment]
Maybe an endpoint exists in plex to return only the changeset between temporal intervals? Media importer could provide an approach similar to what kodi already does:

1 - A fast path only checking what has changed - similar to the functionality kodi has on startup to look only for new items on media sources
2- A slow path/"clean library" approach similar to what kodi has that cleans and scrapes the whole library again. This would be equivalent to a complete sync similar to what is now implemented

**Comment by JeordyR** [comment]
The API supports filters that would enable this functionality.

`/library/sections/<Section>/all?lastViewedAt>=<Epoch Time>`
`/library/sections/41/all?lastViewedAt>=1590012241`
and
`/library/sections/<Section>/all?updatedAt>=<Epoch Time>`
`/library/sections/<Section>/all?updatedAt>=1590012241`

Would be the relevant ones that would filter the results down to things that have either been watched or created/updated in the plex database since the specified time. Set to '0' to make sure you get everything, or `int(time.time()) - 3600` for everything changed within the last hour, for example.

They can be added together, but from the docs it looks like that would be an &&, not an ||, so would probably want to make the calls separately and combine the results.

Need to familiarize myself with this code and whole Kodi plugin ecosystem, but might take a stab at a PR to add this functionality.

**Comment by Montellese** [comment]
@JeordyR thanks for the input. How does `lastViewedAt` work? Is that "last watched" or "last looked at the details" or something else? `updatedAt` sounds very promising 👍 

As a side note I was working together with one of the maintainers of `python-plexapi` and he added some stuff to the library to improve retrieving all items of large libraries. Unfortunately I haven't gotten around to integrate them yet.

**Comment by JeordyR** [comment]
@Montellese Did some testing to verify what those actually represent. 

lastViewedAt is a timestamp for when the item was last toggled to "watched". If an item is "unwatched" in the plex database, the value does not exist. When it gets marked watched, the value gets populated with a timestamp of when it was watched.

updatedAt is a timestamp for when the item was last updated. Being watched does not trigger this to be updated, only refreshing the metadata or changing it manually. This is always set as plex performs an update immediately after creation as it populates the metadata initially.

Also confirmed that &'ing them together into the same call is an && operation, so isn't really viable as it could exclude items that have updated within the delta, but with a lastViewedAt outisde of it (or vice versa). But doing them separately and combing should get a full list of all items that have either been added, updated, or watched.


I found the issue and PR that was done to the plex library you referenced. I'll see about incorporating that in as well for pagination on the full scan as well as pagination on the delta scans if possible. Btw, is there a reason the plex-api library is copied into the repo instead of in the dependencies like the other external libs?

**Comment by Montellese** [comment]
I had to modify some imports of `python-plexapi` because they aren't available in Kodi. But the same maintainer has improved that as well so it's worth looking into whether it is fully compatible now. See https://github.com/Montellese/python-plexapi/commits/kodi for the changes I made.

Also checkout 122a6af0b7b9cf157fa24d7368cbc33323bab058 where I started working on chunked retrieval but based on custom adjustments to `python-plexapi`. But the general approach should still be valid...

**Comment by JeordyR** [comment]
@Montellese Thanks for the context, I'll dig into those.

Do you have the xbmcmediaimport library documented anywhere? I haven't had any luck finding anything.

**Comment by Montellese** [comment]
Unfortunately not. You'll have to read the C++ function definitions at
* `xbmcmediaimport`: https://github.com/Montellese/xbmc/blob/media_import_rebase_20200428/xbmc/interfaces/legacy/ModuleXbmcmediaimport.h
* `xbmcmediaimport.MediaProvider`: https://github.com/Montellese/xbmc/blob/media_import_rebase_20200428/xbmc/interfaces/legacy/mediaimport/MediaProvider.h
* `xbmcmeidaimport.MediaImport`: https://github.com/Montellese/xbmc/blob/media_import_rebase_20200428/xbmc/interfaces/legacy/mediaimport/MediaImport.h

And you can also look at the code I wrote for `mediaimporter.emby` which already supports both full and fast sync, see e.g. https://github.com/Montellese/mediaimporter.emby/blob/master/lib/importer.py#L687-L722 and https://github.com/Montellese/mediaimporter.emby/blob/master/lib/importer.py#L802-L819.

**Comment by JeordyR** [comment]
@Montellese Perfect, thanks! I've been going through the code and adding type hints and docstrings as I go. Will have a PR with those changes soon, in the process of testing to make sure I didn't fat-finger anything and break something.

**Comment by JeordyR** [comment]
FYI @Montellese Looks like they way they implemented pagination into the plexapi lib is fully controlled within the library. We can pass in a container size and a starting point, but they go through and loop through all the pages from that starting point in chunks of the defined size and return the total result instead of leaving control of the pagination to the client.

Some logs of variables while I was debugging with it happening:
```
initial sectionProgressTotal: 102
sectionProgress: 0

<inside pagination loop>
sectionProgressTotal: 102
maxResults: 100
itemsToImport size: 102 (response from the search call)
<end loop>
```
Should have looped twice in this situation, pulling 100, then pulling 2.

Also in a separate note, the .totalSize attribute only reflects the number of video items in the section. When we went to pull the collections from that section, the .totalSize attribute stayed 102, but it only ever found 2 collections, breaking our ability to control the pagination further.

Going to settle for passing in the container size of 100 so they at least use pagination and move on to the delta sync for now.

**Comment by Montellese** [comment]
Reading through the PRs (https://github.com/pkkid/python-plexapi/pull/464 and https://github.com/pkkid/python-plexapi/pull/466) based on my feature request (https://github.com/pkkid/python-plexapi/issues/461) I would expect that you can do something like
```
section.search(
    libtype=plexLibType,
    maxresults=ITEM_REQUEST_LIMIT.
    container_size=ITEM_REQUEST_LIMIT,
    container_start=X)
```
i.e. setting both `maxresults` and `container_size` to the same value and `X` would be increased by `ITEM_REQUEST_LIMIT` after every request until `section.totalSize` is reached. If that doesn't work then that's a bug in `python-plexapi` and I'm sure they are willing to fix it.

Concerning collections I have to look into the code again. I don't even remember how we retrieve them.

**Comment by Montellese** [comment]
Ah now I understood your comment concerning collections. Isn't this also an issue for tvshows, seasons and episodes? They are all retrieved from the same `plexapi.LibrarySection` so the first request on it will evaluate `totalSize` and then for the next requests it is not re-evaluated.

The same issue probably applies when using `plexapi.LibrarySection.search()` with different filters because then each result may return a different amount of items.

**Comment by JeordyR** [comment]
It did end up working out by checking totalSize after calling search(). totalSize is initially populated with that top-level count of items, then gets updated to the relevant number after an initial search is performed.

For one of my test libraries it started out as 102 (number of movies), then after search was done for collections it dropped down to 2 (number of collection in that lib). That's why I ended up defaulting sectionProgressTotal to 100, then updating it within the section loop after the first search is done.

Visually on the progress this doesn't seem to cause any issue (being 0/100 then 2/2; or 0/100 then 100/2500 with the case of TV episodes growing after first-run)

**Comment by Montellese** [comment]
Ah great :+1:
