### ISSUE TITLE
External subtitles

### ISSUE THREAD

**Issue by Montellese** [Montellese/mediaimporter.plex#11]
How to support external subtitles available on the server for a video?

**Comment by enen92** [comment]
I would suggest to leave that to python. The media importer addon could have a plugin extension point and the items stored in the database would be in the form of `plugin://mediaimporter.plex/play/id` instead of simply the id. That way you can use the plugin to create the final listitem and add subtitles to the item.
In the end: `setResolvedUrl` would translate the `plugin://`path to the stream url

**Comment by Montellese** [comment]
Yeah I've also thought about something like that. Right now during importing I already create the "final" stream URL so no more interaction with the add-on is necessary to play a video. For `mediaimporter.emby` I've extended the `Player` class to retrieve the external subtitles from the Emby server when playback is started and then use `Player.addSubtitle()` to add them to the currently playing item.

I have not checked `python-plexapi` yet if there is a way to retrieve (external) subtitles.
